version: "3.8"
services:
  fe-task:
    build:
      context: ./
      dockerfile: scrpits/fe.dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: app:fe-task
    container_name: fe_container
    command: npm start
  be-task:
    build:
      context: ./
      dockerfile: scrpits/be.dockerfile
    volumes:
      - .:/be-task
    ports:
      - 8000:8000
    image: app:be-task
    container_name: be_container
    command: go run main.go